### ISSUE TITLE
Problem: Binaries with latest patches of `cosmos-sdk` and `ibc-go` are not released

### ISSUE THREAD

**Issue by devashishdxt** [crypto-org-chain/chain-main#710]
- [x] Upgrade `cosmos-sdk` to `v0.44.6` (#711)
- [x] Upgrade `ibc-go` to `v2.0.3` (#711)
- [x] Swagger UI security upgrade (#704)
- [x] Update `gomod2nix` (#711)
- [x] Update `cosmos-sdk` submodule (#711)
- [x] Add changelog (#711)
- [x] Merge changes to `release/v3` branch (#712)
- [x] Bump version (https://github.com/crypto-org-chain/chain-main/tree/v3.3.4)
- [x] Release binaries (https://github.com/crypto-org-chain/chain-main/releases/tag/v3.3.4)

**Comment by tomtau** [comment]
+ swagger UI security upgrade

**Comment by tomtau** [comment]
reference: https://github.com/crypto-org-chain/cronos/pull/346/files

**Comment by devashishdxt** [comment]
Released binaries: https://github.com/crypto-org-chain/chain-main/releases/tag/v3.3.4
