### ISSUE TITLE
Problem: Interchain accounts are not enabled in `chain-main`

### ISSUE THREAD

**Issue by devashishdxt** [crypto-org-chain/chain-main#719]
`ibc-go v3.0.0` introduced interchain accounts which can be enabled on chain-main. https://github.com/cosmos/ibc-go/blob/main/docs/migrations/v2-to-v3.md#ics27

**Development plan**:

To enable interchain accounts in `chain-main`, we need following things:

- [x] Create ICA auth module (#730)
- [x] Integrate ICA auth module, ICA controller keeper and ICA host keeper in `app.go` and write upgrade handler (#732)
- [x] Write integration tests for interchain accounts (#733)

For each of the above mentioned steps, a separate PR will be created so that it is easy for review the code in PR.
